version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: health-backend
    ports:
      - "8080:8080"
    environment:
      # łączy się do kontenerowego Postgresa zamiast do localhost
      SPRING_DATASOURCE_URL:       jdbc:postgresql://db:5432/healthdb
      SPRING_DATASOURCE_USERNAME:  postgres
      SPRING_DATASOURCE_PASSWORD:  asd
      # NIE «none» – pozwól Liquibase i JPA zweryfikować/syncnąć schemat
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: health-postgres
    environment:
      POSTGRES_DB:       health-reservation-system
      POSTGRES_USER:     postgres
      POSTGRES_PASSWORD: asd
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
