name: Backend CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SPRING_PROFILES_ACTIVE: test
      JWT_SECRET: test-test-test-12345678901234567890
      SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/health-reservation-system
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: asd
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    

    services:
      postgres:
        image: postgres:15
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: health-reservation-system
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: asd
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven

      - name: Build with Maven
        working-directory: ./backend
        run: mvn -B clean install -Dspring.profiles.active=test

      - name: Build Docker image
        working-directory: ./backend
        run: docker build -t health-reservation-system .
