name: Deploy Backend to Cloud Run

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'backend/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # 1) Uwierzytelnianie JSON-em przez auth@v1
      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # 2) Instalacja/konfiguracja gcloud CLI przez setup-gcloud@v2
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Build & Push Docker image
        working-directory: backend
        run: |
          docker build -t europe-west1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/health-repo/health-backend:${{ github.sha }} .
          gcloud auth configure-docker europe-west1-docker.pkg.dev
          docker push europe-west1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/health-repo/health-backend:${{ github.sha }}

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy health-backend \
            --image europe-west1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/health-repo/health-backend:${{ github.sha }} \
            --region ${{ secrets.GCP_REGION }} \
            --platform managed \
            --allow-unauthenticated \
            --set-env-vars DATABASE_URL=${{ secrets.DATABASE_URL }},JWT_SECRET=${{ secrets.JWT_SECRET }}
