name: Backend CI

on:
  workflow_dispatch:
  push:
    paths:
      - 'backend/**'
    branches: [ main ]
  pull_request:
    paths:
      - 'backend/**'

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: health-reservation-system
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: asd
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Cache Maven deps
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('backend/pom.xml') }}


      - name: Build Docker image
        working-directory: backend
        run: mvn clean verify -Ptest --batch-mode
