name: Frontend CI

on:
  workflow_dispatch:
  push:
    paths:
      - 'frontend/**'
    branches: [ main ]
  pull_request:
    paths:
      - 'frontend/**'

jobs:
  lint-test-build:
    runs-on: ubuntu-latest
    env:
      VITE_API_URL: http://localhost:8080

    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - name: Install dependencies
        working-directory: frontend
        run: npm ci
    #  - name: Lint
    #   working-directory: frontend
     #   run: npm run lint
      - name: Build
        working-directory: frontend
        run: npm run build

